### ISSUE TITLE
Use SQLite rather than MySQL

### ISSUE THREAD

**Issue by andrewfogg** [Bam4d/importSQL#1]
SQLite is native to Python and does not require the installation of any external libraries.  Theoretically then it should be possible for a user to get started with the demo with just pure copy-paste and no installation of other libraries.

**Comment by Bam4d** [comment]
I wanted to make it version agnostic and allow people to easily make it compatible with any SQL server at any address.

The user can use sqlite if they want to, theres no reason to not use this with SQLlite if the user wants to. The scripts don't set up anything server related. its just used as a client

**Comment by andrewfogg** [comment]
makes sense
ᐧ

On 17 February 2015 at 10:42, Chris Bamford notifications@github.com
wrote:

> I wanted to make it version agnostic and allow people to easily make it
> compatible with any SQL server at any address.
> 
> The user can use sqlite if they want to, theres no reason to not use this
> with SQLlite if the user wants to. The scripts don't set up anything server
> related. its just used as a client
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bam4d/importSQL/issues/1#issuecomment-74648542.

## 

Andrew Fogg
Founder & CDO
Import.io http://www.import.io/

US: + 1 (415) 999 7057
UK: + 44 7841 705 144
Skype: andrewfogg
Facebook http://facebook.com/andrewfogg | LinkedIn
http://uk.linkedin.com/in/andrewpeterfogg/ | Twitter
http://www.twitter.com/andrewfogg

1355 Market Street, Suite 488
San Francisco CA 94103 USA

Voted Best Startup By: Web Summit, O'Reilly Strata and GigaOM
