### ISSUE TITLE
Optionally put in timestamps for data collection

### ISSUE THREAD

**Issue by AlexGImson** [Bam4d/importSQL#4]
we should be able to generate a timestamp if there is not one present and add it to the rows of data when they go into the database

**Comment by andrewfogg** [comment]
+1 this is a great suggestion

**Comment by nckltcha** [comment]
As a workaround I've created a trigger on the table in mysql to insert the current date and time

**Comment by CodeOneTwo** [comment]
I added a date field on my fork. https://github.com/CodeOneTwo/importSQL I'll create a Pull request for this, if you like my approach. (Currently only an addDate option is available)

**Comment by CodeOneTwo** [comment]
https://github.com/Bam4d/importSQL/pull/9
